# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3b58fe7906c19f0cbab88e2dbad1186d209abb13881870e3ed6f4afc400629229f6739e3db1b67f0c50ecb09d7e24ac952c141e58a07011b06400f3f0655913

test:
  secret_key_base: 5343fb8d92fc096d6ca0ce6fa864e6ec0b792b0f626bc134814179d44a794c006b030cd0250cacf7b14bc59b86d98948255b6bb740964964ea0c463722fb7d65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
